### ISSUE TITLE
issue bfe42cb

### ISSUE THREAD

**Issue by AkashSingh00** [aniruddha0pandey/Code-Archive#1]
It cannot regonise invalid pattern. @aniruddha0pandey

**Comment by pandevim** [comment]
> @kabir55 Thank You for addressing this  error!

As you can see in the [code](https://github.com/aniruddha0pandey/Code_Archive/blob/master/Archive/Pattern_Prediction.cpp) or these lines below.

https://github.com/aniruddha0pandey/Code_Archive/blob/e2872ff17804b341ce759864c03a31e29787266b/Archive/Pattern_Prediction.cpp#L13-L17

I'm iterating using **Difference Table Method** .
But forgot to check whether the `Difference Nodes` are equal or not.

I'm definitely going to work on this, but don't outwit yourself to tinker with the source..
:fire: Looking forward to your Pull Request.

**Comment by AkashSingh00** [comment]
@aniruddha0pandey  I really appreciate your work , but this code contains one more error and that it works only for increasing numbers.
